# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 873eaa6b9afb33b8b235ac983af474bd4fd2d62d44aedfe292aab09373a099bc11303b4d97960739ec91f2de034ade08d0e123ae879bb673425f44c47ff87f8c

test:
  secret_key_base: 64b8e91d78bfd039d063b0922601bac65b64ffeefe9644cccb66a074809fb8042cf181766e7d6f581e882d330fee2ff6a88ed9ede5b2f0d3a999f585c4f2d110

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
